# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1f6e8a9fffa965ecf983d64ed02f99d6b44cd829fa7222eec84dd5ad7db103bfe854b92ed370bfb5236b44637369279967e1fb12c47695d98c5706763e1261

test:
  secret_key_base: c8add3ff1d49cfbc3a6dd0c357420bc263bbd5701d0af40f3c95c285b7ac9fc5bb980341c6e2ad389596d9726ea94690467e173f9275aafff4acd6415da06cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
